version: '3.3'
services:
  master_1:
    image: mariadb:10.5.4
    command: [ 
      # Replication variables
      '--server_id=1',
      '--log-bin',
      '--log_slave_updates=1',
      '--gtid_domain_id=1',
      '--auto_increment_increment=2',
      '--auto_increment_offset=1',
      # InnoDB variables
      '--innodb_buffer_pool_size=1G',
      '--innodb_flush_log_at_trx_commit=2',
      '--innodb_flush_method=O_DIRECT',
      '--innodb_thread_concurrency=0',
      '--innodb_read_io_threads=64',
      '--innodb_write_io_threads=64',
      '--innodb_io_capacity=2000',
      # Other fine tuning',
      '--max_allowed_packet=1024M',
      '--max_connect_errors=4294967295',
      '--max_connections=2600',
      # Logging
      '--slow-query_log_file=/var/lib/mysql/mariadb-slow.log',
      '--slow_query_log=1',
      '--long_query_time=1'
      ]
    restart: always
    environment:
      #MYSQL_DATABASE: ''
      MYSQL_USER: 'superuser'
      MYSQL_PASSWORD: 'superpass'
      MYSQL_ROOT_PASSWORD: 'rootpass'
    ports:
      - '3306:3306'
      - '122:22'
    expose:
      - '3306'
      - '22'
    volumes:
      - ./master-1/secrets:/docker-entrypoint-initdb.d
      - ./master-1/conf.d:/etc/mysql/mariadb.conf.d 
  master_2:
    image: mariadb:10.5.4
    command: [ 
      # Replication variables
      '--server_id=2',
      '--log-bin',
      '--log_slave_updates=1',
      '--gtid_domain_id=2',
      '--auto_increment_increment=2',
      '--auto_increment_offset=2',
      # InnoDB variables
      '--innodb_buffer_pool_size=1G',
      '--innodb_flush_log_at_trx_commit=2',
      '--innodb_flush_method=O_DIRECT',
      '--innodb_thread_concurrency=0',
      '--innodb_read_io_threads=64',
      '--innodb_write_io_threads=64',
      '--innodb_io_capacity=2000',
      # Other fine tuning',
      '--max_allowed_packet=1024M',
      '--max_connect_errors=4294967295',
      '--max_connections=2600',
      # Logging
      '--slow-query_log_file=/var/lib/mysql/mariadb-slow.log',
      '--slow_query_log=1',
      '--long_query_time=1'
      ]
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'superuser'
      MYSQL_PASSWORD: 'superpass'
      MYSQL_ROOT_PASSWORD: 'rootpass'
    ports:
      - '3307:3306'
      - '123:22'
    expose:
      - '3306'
      - '22'
    volumes:
      - ./master-2/secrets:/docker-entrypoint-initdb.d
      - ./master-2/conf.d:/etc/mysql/mariadb.conf.d 
  slave:
    image: mariadb:10.5.4
    command: [ 
      # Replication variables
      '--server_id=3',
      '--log-bin',
      '--log_slave_updates=1',
      '--gtid_domain_id=3',
      # InnoDB variables
      '--innodb_buffer_pool_size=1G',
      '--innodb_flush_log_at_trx_commit=2',
      '--innodb_flush_method=O_DIRECT',
      '--innodb_thread_concurrency=0',
      '--innodb_read_io_threads=64',
      '--innodb_write_io_threads=64',
      '--innodb_io_capacity=2000',
      # Other fine tuning',
      '--max_allowed_packet=1024M',
      '--max_connect_errors=4294967295',
      '--max_connections=2600',
      '--read_only=1',
      # Logging
      '--slow-query_log_file=/var/lib/mysql/mariadb-slow.log',
      '--slow_query_log=1',
      '--long_query_time=1'
      ]
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'superuser'
      MYSQL_PASSWORD: 'superpass'
      MYSQL_ROOT_PASSWORD: 'rootpass'
    ports:
      - '3308:3306'
      - '124:22'
    expose:
      - '3306'
      - '22'
    volumes:
      - ./slave-1/conf.d:/etc/mysql/mariadb.conf.d 
